#Configuration

#Datasets
block_dataset_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\block
hc_dataset_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\hccsv
energyexport_dataset_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\energy_f.csv
energy_dataset_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\block\block_2.csv
weather_dataset_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_29\weather_hourly_darksky.csv
holiday_dataset_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\raw_datasets\uk_bank_holidays.csv

householdfinancial_data_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\raw_datasets\informations_households.csv
energy_affluent_data_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\energy_affluent.csv
energy_comfortable_data_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\energy_comfortable.csv
energy_adversity_data_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\energy_adversity.csv
energy_allsum_data_path: C:\Users\Furkan\Desktop\DS502_Project\dataspark\datasets\ds_106\energy_allsum.csv

energyfinal_data_path: datasets\final_datasets\energy_final.csv
energyfinal_affluent_data_path: datasets\final_datasets\energyfinal_affluent.csv
energyfinal_comfortable_data_path: datasets\final_datasets\energyfinal_comfortable.csv
energyfinal_adversity_data_path: datasets\final_datasets\energyfinal_adversity.csv

#LOGGER
log_level: DEBUG
log_path: logs/log_file.log
logger_name: main_logger

#FRONT END
gui_path: frontend/Welcome_Page.py
uploaded_file_saving_location: artifacts/uploaded_files

#BACKEND

#MLOPS
api_url: http://127.0.0.1:8000
serving_script_path: deployment

#Production Data

adversity_home_predictions: datasets/production_data/adversity_home_predictions.csv
affluent_home_predictions: datasets/production_data/affluent_home_predictions.csv
all_home_predictions: datasets/production_data/all_home_predictions.csv
comfortable_home_predictions: datasets/production_data/comfortable_home_predictions.csv
daily_average: datasets/production_data/daily_average.csv
daily_average_with_holiday: datasets/production_data/daily_average_with_holiday.csv
daily_high: datasets/production_data/daily_high.csv
daily_high_with_holiday: datasets/production_data/daily_high_with_holiday.csv
daily_low: datasets/production_data/daily_low.csv
daily_low_with_holiday: datasets/production_data/daily_low_with_holiday.csv
daily_total: datasets/production_data/daily_total.csv
daily_total_with_holiday: datasets/production_data/daily_total_with_holiday.csv
data_describe: datasets/production_data/data_describe.csv
data_describe_all: datasets/production_data/data_describe_all.csv
monthly_average: datasets/production_data/monthly_average.csv
monthly_high: datasets/production_data/monthly_high.csv
monthly_low: datasets/production_data/monthly_low.csv
monthly_total: datasets/production_data/monthly_total.csv
uk_bank_holidays: datasets/production_data/uk_bank_holidays.csv
performance_metrics: datasets/production_data/performance_metrics.csv
