name: dataspark_env
channels:
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3

  - pip:
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - altair==5.1.2
    - annotated-types==0.6.0
    - anyio==3.7.1
    - appdirs==1.4.4
    - asgiref==3.7.2
    - async-timeout==4.0.3
    - attrs==23.1.0
    - beautifulsoup4==4.12.2
    - bentoml==1.1.9
    - blinker==1.7.0
    - build==1.0.3
    - cachetools==5.3.2
    - cattrs==23.1.2
    - certifi==2023.7.22
    - charset-normalizer==3.3.2
    - circus==0.18.0
    - click==8.1.7
    - click-option-group==0.5.6
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - contextlib2==21.6.0
    - contourpy==1.2.0
    - cycler==0.12.1
    - dacite==1.8.1
    - deepmerge==1.1.0
    - deprecated==1.2.14
    - docopt==0.6.2
    - entrypoints==0.4
    - exceptiongroup==1.1.3
    - faker==20.1.0
    - fastapi==0.105.0
    - favicon==0.7.0
    - fonttools==4.44.0
    - frozenlist==1.4.0
    - fs==2.4.16
    - gitdb==4.0.11
    - gitpython==3.1.40
    - h11==0.14.0
    - htbuilder==0.6.2
    - htmlmin==0.1.12
    - httpcore==1.0.2
    - httpx==0.25.1
    - idna==3.4
    - imagehash==4.3.1
    - importlib-metadata==6.8.0
    - inflection==0.5.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - kaleido==0.2.1
    - kiwisolver==1.4.5
    - llvmlite==0.41.1
    - lxml==4.9.3
    - markdown==3.5.1
    - markdown-it-py==3.0.0
    - markdownlit==0.0.7
    - markupsafe==2.1.3
    - matplotlib==3.8.1
    - mdurl==0.1.2
    - more-itertools==10.1.0
    - multidict==6.0.4
    - multimethod==1.10
    - networkx==3.2.1
    - numba==0.58.1
    - numpy==1.25.2
    - nvidia-ml-py==11.525.150
    - opentelemetry-api==1.20.0
    - opentelemetry-instrumentation==0.41b0
    - opentelemetry-instrumentation-aiohttp-client==0.41b0
    - opentelemetry-instrumentation-asgi==0.41b0
    - opentelemetry-sdk==1.20.0
    - opentelemetry-semantic-conventions==0.41b0
    - opentelemetry-util-http==0.41b0
    - packaging==23.2
    - pandas==2.1.3
    - pandas-profiling==3.6.6
    - pathspec==0.11.2
    - patsy==0.5.4
    - phik==0.12.3
    - pillow==10.1.0
    - pip-requirements-parser==32.0.1
    - pip-tools==7.3.0
    - pipreqs==0.4.13
    - plotly==5.18.0
    - prettytable==3.9.0
    - prometheus-client==0.18.0
    - protobuf==4.25.0
    - psutil==5.9.6
    - pyarrow==14.0.1
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pydeck==0.8.1b0
    - pyecharts==2.0.4
    - pygments==2.16.1
    - pymdown-extensions==10.5
    - pyparsing==3.1.1
    - pyproject-hooks==1.0.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-multipart==0.0.6
    - pytz==2023.3.post1
    - pywavelets==1.5.0
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - referencing==0.30.2
    - requests==2.31.0
    - rich==13.6.0
    - rpds-py==0.12.0
    - schema==0.7.5
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - seaborn==0.12.2
    - simple-di==0.1.5
    - simplejson==3.19.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - st-annotated-text==4.0.1
    - starlette==0.27.0
    - statsmodels==0.14.1
    - stqdm==0.0.5
    - streamlit==1.28.2
    - streamlit-camera-input-live==0.2.0
    - streamlit-card==0.0.61
    - streamlit-echarts==0.4.0
    - streamlit-embedcode==0.1.2
    - streamlit-extras==0.3.5
    - streamlit-faker==0.0.3
    - streamlit-image-coordinates==0.1.6
    - streamlit-keyup==0.2.0
    - streamlit-pandas-profiling==0.1.3
    - streamlit-toggle-switch==1.0.2
    - streamlit-vertical-slider==1.0.2
    - tangled-up-in-unicode==0.2.0
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.3.3
    - tqdm==4.66.1
    - typeguard==4.1.5
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - tzlocal==5.2
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - validators==0.22.0
    - visions==0.7.5
    - watchdog==3.0.0
    - watchfiles==0.21.0
    - wcwidth==0.2.12
    - wordcloud==1.9.3
    - wrapt==1.16.0
    - yarg==0.1.9
    - yarl==1.9.2
    - ydata-profiling==4.6.3
    - zipp==3.17.0